use mathverse_plot::export::ExportConfig;
use mathverse_plot::theme::ThemeConfig;
use mathverse_plot::axis_config::AxisConfig;

fn main() {
    // Create export config
    let export = ExportConfig::new()
        .with_dimensions(800, 600)
        .with_background(mathverse_plot::style::Color::WHITE)
        .with_title("Customization Demo")
        .with_footer("Generated by mathverse-plot")
        .with_watermark("DRAFT");

    // Create theme
    let theme = ThemeConfig::seaborn();

    // Create axis config
    let axis = AxisConfig::new()
        .with_label("x-axis")
        .with_grid()
        .with_tick_rotation(45.0);

    // Generate SVG parts
    let header = export.svg_header();
    let theme_header = theme.svg_header(export.width, export.height);
    let footer = export.svg_footer();
    let (x, y, w, h) = export.plot_area();

    println!("SVG dimensions: {}x{}", export.width, export.height);
    println!("Plot area: ({}, {}, {}, {})", x, y, w, h);
    println!("Theme header length: {} chars", theme_header.len());
    println!("Header length: {} chars", header.len());
    println!("Footer length: {} chars", footer.len());
    println!("Customization demo complete!");
}
